services:
  app:
    image: ${GIT_REGISTRY}/${GIT_USER}/${GIT_REPO}:${IMAGE_TAG:-latest}
    ports:
      - "${EXTERNAL_PORT:-8098}:${PORT}"
    environment:
      - PORT=${PORT}
      - FLASK_DEBUG=false
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - HOST=${HOST}
    depends_on:
      postgres:
        condition: service_healthy
    command:
      [
        "/app/bin/gunicorn",
        "--bind",
        ":${PORT}",
        "--workers",
        "1",
        "--threads",
        "8",
        "python_example.app:app",
      ]
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
