name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Create .env file
        run: |
          cp .env.example .env

      - name: Install dependencies
        run: uv sync --dev

      - name: Run all checks
        run: just check-all